#! /usr/bin/env python3
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 7.6
#  in conjunction with Tcl version 8.6
#    Mar 17, 2023 08:33:32 PM GMT  platform: Windows NT

import sys
import tkinter as tk
import tkinter.ttk as ttk
from tkinter.constants import *
import random

import tkinter_ui_gpt_euromilhoes

_debug = True # False to eliminate debug printing from callback functions.

def main(*args):
    '''Main entry point for the application.'''
    global root
    root = tk.Tk()
    root.protocol( 'WM_DELETE_WINDOW' , root.destroy)
    # Creates a toplevel widget.
    global _top1, _w1
    _top1 = root
    _w1 = tkinter_ui_gpt_euromilhoes.window(_top1)
    root.mainloop()

def draw_numbers():
    most_frequent_numbers = [1, 2, 4, 6, 7, 9, 10, 11, 12, 13, 15, 16, 18, 19, 20, 21, 23, 24, 27, 28, 29, 30, 33, 34, 36, 38, 39, 40, 41, 43, 45, 46, 47, 49, 50]
    probabilities = [0.087, 0.071, 0.07, 0.07, 0.07, 0.068, 0.068, 0.068, 0.067, 0.065, 0.065, 0.065, 0.065, 0.063, 0.062, 0.06, 0.059, 0.059, 0.058, 0.058, 0.057, 0.056, 0.055, 0.054, 0.052, 0.051, 0.049, 0.048, 0.047, 0.045, 0.044, 0.042, 0.042, 0.039, 0.039]
    numbers = random.choices(most_frequent_numbers, probabilities, k=5)
    stars = random.sample(range(1, 12), 2)
    _w1.numbers_label.config(text="Números: " + " ".join(str(num) for num in numbers))
    _w1.star_label.config(text="Estrela: " + str(stars[0]) + " " + str(stars[1]))

if __name__ == '__main__':
    tkinter_ui_gpt_euromilhoes.start_up()




