#! /usr/bin/env python3
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 7.6
#  in conjunction with Tcl version 8.6
#    Mar 17, 2023 08:51:35 PM GMT  platform: Windows NT

import sys
import tkinter as tk
import tkinter.ttk as ttk
from tkinter.constants import *
import os.path

_script = sys.argv[0]
_location = os.path.dirname(_script)

import tkinter_ui_gpt_euromilhoes_support

_bgcolor = '#d9d9d9'  # X11 color: 'gray85'
_fgcolor = '#000000'  # X11 color: 'black'
_compcolor = 'gray40' # X11 color: #666666
_ana1color = '#c3c3c3' # Closest X11 color: 'gray76'
_ana2color = 'beige' # X11 color: #f5f5dc
_tabfg1 = 'black' 
_tabfg2 = 'black' 
_tabbg1 = 'grey75' 
_tabbg2 = 'grey89' 
_bgmode = 'light' 

class window:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''

        top.geometry("300x200+150+150")
        top.minsize(300, 200)
        top.maxsize(1924, 1037)
        top.resizable(1,  1)
        top.title("GPT EUROMILHÕES")
        top.configure(relief="groove")
        top.configure(background="#d9d9d9")

        self.top = top

        self.numbers_label = tk.Label(self.top)
        self.numbers_label.place(relx=0.033, rely=0.16, height=31, width=270)
        self.numbers_label.configure(background="#d9d9d9")
        self.numbers_label.configure(compound='left')
        self.numbers_label.configure(disabledforeground="#a3a3a3")
        self.numbers_label.configure(font="-family {Segoe UI} -size 14")
        self.numbers_label.configure(foreground="#000000")
        self.numbers_label.configure(text='''Numeros: 00 00 00 00 00''')
        self.star_label = tk.Label(self.top)
        self.star_label.place(relx=0.033, rely=0.315, height=32, width=270)
        self.star_label.configure(activebackground="#f9f9f9")
        self.star_label.configure(background="#d9d9d9")
        self.star_label.configure(compound='left')
        self.star_label.configure(disabledforeground="#a3a3a3")
        self.star_label.configure(font="-family {Segoe UI} -size 14")
        self.star_label.configure(foreground="#000000")
        self.star_label.configure(highlightbackground="#d9d9d9")
        self.star_label.configure(highlightcolor="black")
        self.star_label.configure(text='''Estrelas: 00 00''')
        self.draw_button = tk.Button(self.top)
        self.draw_button.place(relx=0.033, rely=0.575, height=68, width=280)
        self.draw_button.configure(activebackground="#85ef52")
        self.draw_button.configure(activeforeground="black")
        self.draw_button.configure(background="#d9d9d9")
        self.draw_button.configure(command=tkinter_ui_gpt_euromilhoes_support.draw_numbers)
        self.draw_button.configure(compound='left')
        self.draw_button.configure(disabledforeground="#a3a3a3")
        self.draw_button.configure(font="-family {Segoe UI} -size 16 -weight bold")
        self.draw_button.configure(foreground="#000000")
        self.draw_button.configure(highlightbackground="#d9d9d9")
        self.draw_button.configure(highlightcolor="black")
        self.draw_button.configure(pady="0")
        self.draw_button.configure(text='''SORTEAR''')
        self.menubar = tk.Menu(top,font="TkMenuFont",bg=_bgcolor,fg=_fgcolor)
        top.configure(menu = self.menubar)

def start_up():
    tkinter_ui_gpt_euromilhoes_support.main()

if __name__ == '__main__':
    tkinter_ui_gpt_euromilhoes_support.main()




